spring:
  application:
   name: config_server_fetching
eureka:
  instance:
    prefer-ip-address: true  # use the IP address of the host where the service is running instead of its hostname
  client:
    fetch-registry: true
    register-with-eureka: true #This property specifies that the service instance should register 
                               #itself with the Eureka server. This allows other services to 
                               #discover and communicate with this service.
    service-url:
      default: http://localhost:8761/eureka
